### ISSUE TITLE
CancellationTokenSource should be disposed

### ISSUE THREAD

**Issue by PauliusLe** [launchdarkly/dotnet-client#100]
There is some places like this one https://github.com/launchdarkly/dotnet-client/blob/cd0b2911aa7a6b92a3815829d8cf522145ea8913/src/LaunchDarkly.Client/FeatureRequestor.cs#L51 where CancellationTokenSource is not disposed. Because CancellationTokenSource is initialized with a timespan it creates a timer internally. This could cause a memory leaks.
https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads

**Comment by eli-darkly** [comment]
I agree that it would be a good practice for us to explicitly dispose of these, and I'll make that change, but just for clarity: I'm not sure it is actually the case that this is risking a leak. The MS docs you linked to don't get into any details, but from all other sources I've been able to find, the issue is not about the user of a timer (which would almost certainly be a managed resource, handled by normal GC), but about the option to create a "linked" token source—which does have the ability to leak, but we're not using linked token sources. I may be wrong and as I said we should clean this up in any case, but I would be very surprised if this was actually causing any leaks.

**Comment by eli-darkly** [comment]
Well, looking further into it I'm seeing somewhat mixed messages as to whether a timer can leak or not. Still, again, we should certainly be disposing.

**Comment by eli-darkly** [comment]
OK, all such cases have been cleaned up in the 5.6.2 release. Thanks for pointing this out.
