### ISSUE TITLE
Target .net standard instead of .net coreapp

### ISSUE THREAD

**Issue by gzak** [launchdarkly/dotnet-client#41]
Since this is a library to be consumed by applications, it ought to target .netstandard (probably at a relatively early version to maximize compatibility) rather than .netcoreapp, since the latter is meant to be targetted by top-level applications rather than libraries.

**Comment by ISkomorokh** [comment]
And I believe `.net standard` 2.0 should be chosen.

**Comment by drichelson** [comment]
Thanks @gzak and @ISkomorokh  for the feedback. 

Agreed on all these points, but .net standard 2.0 is [not out yet](https://github.com/dotnet/standard/milestone/2), so we may wait until that happens to avoid  refactoring the project layout one more time. 

Additional feedback is welcome.

**Comment by ISkomorokh** [comment]
Does anything stops you from starting with [1.1](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.1.md)? All the required platforms are supporting it already

**Comment by bernard-chen** [comment]
If the library can be built with .NET Standard 1.0, it remains compatible even now that .NET Standard 2.0 is out. .NET Standard 2.0 is purely a superset of 1.0 in spite of the major version change.

At this point .NET Standard 2.0 is out. Can we take another look at targeting it instead of .NET Core?
