### ISSUE TITLE
Windows section in Contributing Getting Started Guide

### ISSUE THREAD

**Issue by KimboTodd** [launchdarkly/dotnet-client#94]
After looking through the getting started section, I'm not finding a windows section or answer to an error message while attempting to build launch darkly locally. Any advice on solving the following issue is much appreciated.

The LaunchDarkly.snk is not checked in to this repo, so I get the error ```Error CS7027 Error signing output with public key from file '../../LaunchDarkly.snk' -- File not found.	LaunchDarkly.Client(netstandard2.0)```

If I change the project settings to uncheck "sign the assembly" I get the error message: 
```Error CS0281 Friend access was granted by 'LaunchDarkly.Common.StrongName, Version=1.1.1.0, Culture=neutral, PublicKeyToken=45ef1738a929a7df', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.	LaunchDarkly.Client(netstandard2.0)```

I'm not the most knowledgeable about strong-named assemblies, but I found this: ```If you are an open-source developer and you want the identity benefits of a strong-named assembly, consider checking in the private key associated with an assembly into your source control system.```  https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies
This was also interesting: https://stackoverflow.com/questions/1831248/what-is-the-recommended-way-to-manage-a-strong-name-key-pair-for-an-open-source/52232108#52232108

**Comment by eli-darkly** [comment]
Sorry for the difficulty - we're aware that this particular code is not as friendly to outside developers as it could be. There are two issues here, both of which can be a bit confusing.

1. It normally wants to build a strong-named assembly so, as you saw, it won't work without a key (which is deliberately not checked into the source code, as it contains a private credential). So in the past, developers who wanted to fork the project have generally just turned off the signing property as you tried to do. However...

2. ...We made a change to the project structure which introduces this "friend access" issue. Basically, we have split out some code into a second assembly, whose code is [here](https://github.com/launchdarkly/dotnet-client-common). To avoid making a lot of implementation details public, we used `internal` scope for most of its classes, and added an `InternalsVisibleTo` directive which allows `LaunchDarkly.Client` to access those. However, when `InternalsVisibleTo` references a strong-named assembly, it won't work if that assembly is no longer strong-named.

Here's what I recommend for your immediate development needs:

1. Create a local copy or a fork of the "common" project mentioned above.
2. You'll see that it actually builds two assemblies: `LaunchDarkly.Common` and `LaunchDarkly.Common.StrongName`. Edit `src/LaunchDarkly.Common/AssemblyInfo.cs` and add this line: `[assembly: InternalsVisibleTo("LaunchDarkly.Client")]`.
3. Change the `LaunchDarkly.Client` project to reference `LaunchDarkly.Common` instead of `LaunchDarkly.Common.StrongName`.

As to how we could make this easier in the future, I'm still thinking about it, but there are two things I think would definitely help:

1. We could change `LaunchDarkly.Client` so that if you build it in Debug configuration, it doesn't do signing and it imports `LaunchDarkly.Common` instead of `LaunchDarkly.Common.StrongName`. We haven't done this in the past because our releases were actually being built in Debug configuration, but I don't think there was any good reason for that.
2. We should change `LaunchDarkly.Common` to include the `InternalsVisibleTo` directive mentioned above, to support this type of build. (It's not there now just because _we_ haven't ever built the .NET client without signing - however `LaunchDarkly.Common` is also used by our Xamarin client, currently in beta release, which doesn't use signing.)

I hope that helps...

**Comment by eli-darkly** [comment]
Hi. I have a very slight update: in the latest release of `LaunchDarkly.Common`, we added the directive `InternalsVisibleTo("LaunchDarkly.Client")`, so you do not need to make any changes to `Common` to make it work with a forked un-strong-named version of `Client`. In other words, you would no longer need to do steps 1 and 2 under "Here's what I recommend..."

**Comment by eli-darkly** [comment]
Another update: as of version 5.6.0, the default Debug configuration does not use strong-naming. We're now using the Release configuration for our published packages. So if you want to build locally and you don't mind using Debug configuration, things should be much simpler.

I'll close this issue, but please feel free to reopen it if you have any more concerns of this kind.
